name: 2팀 ISSUE 템플릿
description: 작업용 템플릿입니다.
title: ''
labels: []
assignees: []

body:
  - type: textarea
    id: task-content
    attributes:
      label: ✨ 작업 내용
      description: 무엇을 할 작업인지 간단히 작성해주세요
      placeholder: |
        - 회원가입 API 연동
        - 레이아웃 개선
    validations:
      required: true

  - type: textarea
    id: related-components
    attributes:
      label: 🔍 관련 화면 or 컴포넌트
      description: 해당 작업이 적용될 화면이나 컴포넌트가 있다면 작성해주세요
      placeholder: |
        - LoginPage
        - SignUpForm.jsx

  - type: input
    id: target-date
    attributes:
      label: ⏰ Target 날짜
      description: yyyy-mm-dd 형식으로 입력해주세요. Actions가 자동 인식합니다.
      placeholder: "예: 2025-06-01"
    validations:
      required: true
